version: '3.8'
services:

  webapi:
    container_name: webapi-auth
    build:
      context: .
      dockerfile: ./docker/webapi/Dockerfile
    volumes:
      - ./webapi/:/webapi/
    ports:
      - "8000:8000"
    networks:
      - default
    tty: true
    restart: always
    depends_on:
      rdb:
        condition: service_healthy

  rdb:
    container_name: rdb-auth
    build:
      context: .
      dockerfile: ./docker/rdb/Dockerfile
    volumes:
      - ./rdb/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
    tty: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rdb -d rdb"]
      interval: 10s
      timeout: 10s
      retries: 5


volumes:
  data:
    driver: local


# イメージ作成 & コンテナ起動
## docker-compose up -d --build

# イメージ削除 & コンテナ削除
## docker-compose down --rmi all

